/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface EclButton {
    'styleClass': string;
    'type': string;
  }
  interface EclIcon {
    'color': string;
    'icon': string;
    'size': string;
    'styleClass': string;
    'transform': string;
  }
  interface EclMessage {
    'styleClass': string;
    'title': string;
    'typeClass': string;
  }
  interface EclShowcase {}
  interface EclSvgDefinitions {}
  interface EclTag {
    'isRemovable': boolean;
    'styleClass': string;
  }
}

declare global {


  interface HTMLEclButtonElement extends Components.EclButton, HTMLStencilElement {}
  var HTMLEclButtonElement: {
    prototype: HTMLEclButtonElement;
    new (): HTMLEclButtonElement;
  };

  interface HTMLEclIconElement extends Components.EclIcon, HTMLStencilElement {}
  var HTMLEclIconElement: {
    prototype: HTMLEclIconElement;
    new (): HTMLEclIconElement;
  };

  interface HTMLEclMessageElement extends Components.EclMessage, HTMLStencilElement {}
  var HTMLEclMessageElement: {
    prototype: HTMLEclMessageElement;
    new (): HTMLEclMessageElement;
  };

  interface HTMLEclShowcaseElement extends Components.EclShowcase, HTMLStencilElement {}
  var HTMLEclShowcaseElement: {
    prototype: HTMLEclShowcaseElement;
    new (): HTMLEclShowcaseElement;
  };

  interface HTMLEclSvgDefinitionsElement extends Components.EclSvgDefinitions, HTMLStencilElement {}
  var HTMLEclSvgDefinitionsElement: {
    prototype: HTMLEclSvgDefinitionsElement;
    new (): HTMLEclSvgDefinitionsElement;
  };

  interface HTMLEclTagElement extends Components.EclTag, HTMLStencilElement {}
  var HTMLEclTagElement: {
    prototype: HTMLEclTagElement;
    new (): HTMLEclTagElement;
  };
  interface HTMLElementTagNameMap {
    'ecl-button': HTMLEclButtonElement;
    'ecl-icon': HTMLEclIconElement;
    'ecl-message': HTMLEclMessageElement;
    'ecl-showcase': HTMLEclShowcaseElement;
    'ecl-svg-definitions': HTMLEclSvgDefinitionsElement;
    'ecl-tag': HTMLEclTagElement;
  }
}

declare namespace LocalJSX {
  interface EclButton {
    'styleClass'?: string;
    'type'?: string;
  }
  interface EclIcon {
    'color'?: string;
    'icon'?: string;
    'size'?: string;
    'styleClass'?: string;
    'transform'?: string;
  }
  interface EclMessage {
    'styleClass'?: string;
    'title'?: string;
    'typeClass'?: string;
  }
  interface EclShowcase {}
  interface EclSvgDefinitions {}
  interface EclTag {
    'isRemovable'?: boolean;
    'styleClass'?: string;
  }

  interface IntrinsicElements {
    'ecl-button': EclButton;
    'ecl-icon': EclIcon;
    'ecl-message': EclMessage;
    'ecl-showcase': EclShowcase;
    'ecl-svg-definitions': EclSvgDefinitions;
    'ecl-tag': EclTag;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'ecl-button': LocalJSX.EclButton & JSXBase.HTMLAttributes<HTMLEclButtonElement>;
      'ecl-icon': LocalJSX.EclIcon & JSXBase.HTMLAttributes<HTMLEclIconElement>;
      'ecl-message': LocalJSX.EclMessage & JSXBase.HTMLAttributes<HTMLEclMessageElement>;
      'ecl-showcase': LocalJSX.EclShowcase & JSXBase.HTMLAttributes<HTMLEclShowcaseElement>;
      'ecl-svg-definitions': LocalJSX.EclSvgDefinitions & JSXBase.HTMLAttributes<HTMLEclSvgDefinitionsElement>;
      'ecl-tag': LocalJSX.EclTag & JSXBase.HTMLAttributes<HTMLEclTagElement>;
    }
  }
}


